stages:
  - install
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/Cypress"

cache:
  paths:
    - .npm
    - .cache/Cypress
    - node_modules

default:
  image: cypress/browsers:node-20.11.0-chrome-121.0.6167.85-1

install:
  stage: install
  script:
    - npm ci
    - npx cypress verify
  artifacts:
    paths:
      - node_modules
    expire_in: 1 day

e2e_tests:
  stage: test
  dependencies:
    - install
  script:
    - npm run cy:run:chrome
  artifacts:
    when: always
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 7 days

api_tests:
  stage: test
  dependencies:
    - install
  script:
    - npm run cy:run -- --spec "cypress/e2e/api/**/*.cy.js"
  artifacts:
    when: always
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 7 days